// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV7QMshayx_4IDxzZfrqYtimuGNErO84o',
    appId: '1:490252793395:web:a3291d0f16e868d4d99546',
    messagingSenderId: '490252793395',
    projectId: 'software-2093e',
    authDomain: 'software-2093e.firebaseapp.com',
    storageBucket: 'software-2093e.appspot.com',
    measurementId: 'G-YS16XW5Z93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfkgxQbfaOoAfoGPUOxMsTM1V_mWtnDqE',
    appId: '1:490252793395:android:bffd743916bb8389d99546',
    messagingSenderId: '490252793395',
    projectId: 'software-2093e',
    storageBucket: 'software-2093e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAN1S_Urkh5Ertrg1BBSq54moIl5RYgE',
    appId: '1:490252793395:ios:a6d6b2ef8207159ed99546',
    messagingSenderId: '490252793395',
    projectId: 'software-2093e',
    storageBucket: 'software-2093e.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtAN1S_Urkh5Ertrg1BBSq54moIl5RYgE',
    appId: '1:490252793395:ios:a6d6b2ef8207159ed99546',
    messagingSenderId: '490252793395',
    projectId: 'software-2093e',
    storageBucket: 'software-2093e.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV7QMshayx_4IDxzZfrqYtimuGNErO84o',
    appId: '1:490252793395:web:a1ced2f101e7d0bbd99546',
    messagingSenderId: '490252793395',
    projectId: 'software-2093e',
    authDomain: 'software-2093e.firebaseapp.com',
    storageBucket: 'software-2093e.appspot.com',
    measurementId: 'G-77M6Q8ZVHL',
  );
}
